# Generated by Django 5.1.2 on 2024-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
                ('supervisor', models.CharField(max_length=64)),
                ('organisation', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('room', models.CharField(max_length=16)),
                ('equipment', models.CharField(max_length=64)),
                ('equipmentid', models.CharField(max_length=32)),
            ],
        ),
    ]
