# Generated by Django 5.1.2 on 2024-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentID_auto', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentName', models.CharField(max_length=100)),
                ('hourlyRate', models.FloatField(default=0.0)),
            ],
        ),
    ]
