# Generated by Django 5.1.2 on 2024-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=80)),
                ('cancelled_by', models.CharField(max_length=80)),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
