# Generated by Django 5.1.2 on 2024-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
