# Generated by Django 5.1.2 on 2024-10-24 14:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceRef', models.CharField(max_length=10)),
                ('issueDate', models.DateField(default=django.utils.timezone.now)),
                ('startDate', models.DateField(default=datetime.date(2024, 9, 24))),
                ('finishDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentid', models.CharField(max_length=32)),
                ('equipmentname', models.CharField(default='N/A', max_length=64)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
