# Generated by Django 5.1.2 on 2024-10-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
