# Generated by Django 5.1.2 on 2024-10-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0002_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.AddField(
            model_name='event',
            name='finishTime',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
    ]
