# Generated by Django 5.1.2 on 2024-10-24 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0002_billing_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
        ),
    ]
