# Generated by Django 5.1.2 on 2024-11-07 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0002_cancelledbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='comments',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 8, 7)),
        ),
    ]
