# Generated by Django 5.1.2 on 2024-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0002_alter_bookings_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('supervisor', models.CharField(max_length=64)),
                ('organisation', models.CharField(max_length=128)),
                ('isAccepted', models.BooleanField(default=False)),
            ],
        ),
    ]
