# Generated by Django 5.1.2 on 2024-11-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0003_rename_comments_event_notes_alter_billing_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 8, 19)),
        ),
    ]
