# Generated by Django 5.1.2 on 2024-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0003_alter_billing_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='equipment',
            field=models.ManyToManyField(to='MCalendar.equipment'),
        ),
    ]
