# Generated by Django 5.1.2 on 2024-10-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0003_delete_bookings_event_finishtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finishTime',
        ),
    ]
