# Generated by Django 5.1.2 on 2024-10-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0003_remove_users_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Person',
        ),
    ]
