# Generated by Django 5.1.2 on 2024-10-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0004_rename_users_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
