# Generated by Django 5.1.2 on 2024-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0004_billing_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='totalCost',
            field=models.FloatField(default=0.0),
        ),
    ]
