# Generated by Django 5.1.2 on 2024-10-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0004_remove_event_finishtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='allotedTime',
            new_name='finishTime',
        ),
    ]
