# Generated by Django 5.1.3 on 2024-11-20 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0005_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 8, 20)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
