# Generated by Django 5.1.2 on 2024-10-24 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0005_billing_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='supervisor',
            field=models.ManyToManyField(to='MCalendar.supervisor'),
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
