# Generated by Django 5.1.3 on 2024-11-29 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0005_alter_billing_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 8, 29)),
        ),
        migrations.AlterField(
            model_name='event',
            name='totalTime',
            field=models.FloatField(default=0),
        ),
    ]
