# Generated by Django 5.1.3 on 2024-12-03 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0006_alter_billing_startdate_alter_event_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='event',
            name='hourlyRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
