# Generated by Django 5.1.2 on 2024-11-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0006_event_totaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254),
            preserve_default=False,
        ),
    ]
