# Generated by Django 5.1.2 on 2024-11-03 12:27

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0006_event_totaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceRef', models.CharField(max_length=10)),
                ('issueDate', models.DateField(default=django.utils.timezone.now)),
                ('startDate', models.DateField(default=datetime.date(2024, 8, 3))),
                ('finishDate', models.DateField(default=django.utils.timezone.now)),
                ('totalCost', models.FloatField(default=0.0)),
                ('bookingStuff', models.ManyToManyField(to='MCalendar.event')),
                ('equipment', models.ManyToManyField(to='MCalendar.equipment')),
                ('supervisor', models.ManyToManyField(to='MCalendar.supervisor')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
