# Generated by Django 5.1.2 on 2024-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0006_event_totaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
