# Generated by Django 5.1.2 on 2024-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0006_billing_supervisor_billing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bookingStuff',
            field=models.ManyToManyField(to='MCalendar.bookings'),
        ),
    ]
