# Generated by Django 5.1.2 on 2024-10-18 10:41

import MCalendar.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0007_person_groups_person_is_superuser_person_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', MCalendar.models.CustomUserManager()),
            ],
        ),
    ]
