# Generated by Django 5.1.2 on 2024-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0007_event_customprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hourlyRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
