# Generated by Django 5.1.2 on 2024-11-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0007_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='bookingStuff',
            new_name='events',
        ),
    ]
