# Generated by Django 5.1.2 on 2024-10-27 13:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0007_billing_bookingstuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(default=datetime.datetime(2024, 10, 20, 13, 49, 39, 218027, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='billing',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 7, 27)),
        ),
    ]
