# Generated by Django 5.1.2 on 2024-11-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0007_event_email'),
        ('MCalendar', '0008_rename_bookingstuff_billing_events'),
    ]

    operations = [
    ]
