# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0008_filter_alter_billing_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='endDate',
            field=models.DateField(),
        ),
    ]
