# Generated by Django 5.1.2 on 2024-11-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0008_event_hourlyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customPrice',
        ),
    ]
