# Generated by Django 5.1.2 on 2024-10-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0008_alter_person_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
