# Generated by Django 5.1.2 on 2024-10-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0009_alter_filter_enddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
