# Generated by Django 5.1.2 on 2024-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0010_remove_billing_supervisor_billing_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.CharField(default='userTest', max_length=64),
            preserve_default=False,
        ),
    ]
