# Generated by Django 5.1.2 on 2024-11-03 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0011_remove_billing_user_billing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
