# Generated by Django 5.1.2 on 2024-11-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0012_remove_billing_user_billing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
    ]
