# Generated by Django 5.1.2 on 2024-10-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0012_rename_person_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='person',
        ),
    ]
