# Generated by Django 5.1.2 on 2024-11-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0013_remove_billing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invoiceRef',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
