# Generated by Django 5.1.2 on 2024-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0013_remove_supervisor_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
