# Generated by Django 5.1.2 on 2024-10-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0014_delete_supervisor'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Person',
        ),
    ]
