# Generated by Django 5.1.2 on 2024-10-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCalendar', '0016_rename_person_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=15, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
